export const FETCH_ALBUM_PHOTOS = {
  SUCCESS: "@photos: FETCH_ALBUM_PHOTOS_SUCCESS",
  ERROR: "@photos: FETCH_ALBUM_PHOTOS_ERROR",
  START: "@photos: FETCH_ALBUM_PHOTOS_START"
};

export const FETCH_ALBUMS = {
  SUCCESS: "@photos: FETCH_ALBUMS_SUCCESS",
  ERROR: "@photos: FETCH_ALBUMS_ERROR",
  START: "@photos: FETCH_ALBUMS_START"
};
